name: Generate Changelog

on:
  release:
    types: [created]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    container:
      image: githubchangeloggenerator/github-changelog-generator
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: |
          github_changelog_generator \
            -u ${{ github.repository_owner }} \
            -p ${{ github.event.repository.name }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --since-tag $(git describe --tags --abbrev=0 `git rev-list --tags --skip=1 --max-count=1`) \
            --future-release ${{ github.event.release.tag_name }}

      - name: Commit and Push Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.event.release.tag_name }}"
          git push
