name: Generate Changelog

on:
  release:
    types: [created]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    container:
      image: githubchangeloggenerator/github-changelog-generator
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate Changelog
        run: |
          # Get previous tag or use empty string if none exists
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            # First release - don't use since-tag
            github_changelog_generator \
              -u ${{ github.repository_owner }} \
              -p ${{ github.event.repository.name }} \
              --token ${{ secrets.GITHUB_TOKEN }} \
              --future-release ${{ github.event.release.tag_name }}
          else
            # Subsequent releases - use since-tag
            github_changelog_generator \
              -u ${{ github.repository_owner }} \
              -p ${{ github.event.repository.name }} \
              --token ${{ secrets.GITHUB_TOKEN }} \
              --since-tag $PREV_TAG \
              --future-release ${{ github.event.release.tag_name }}
          fi

      - name: Commit and Push Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
